addr = {'yuxiao.zhai@mail.utoronto.ca','yu.xue@mail.utoronto.ca'};
subj = 'Message from Amanda';
Sgnt = [newline,newline,'This message is automatically generated by MATLAB. Please do not reply.'];

StartMsg = 'A simulation has started.';
EndMsg = 'Simulation completed.';

sendmail(addr,subj,[StartMsg,Sgnt]);

fwb = waitbar(0.5,'Running simulation. Please contact Mike or Yuxiao for terminating.');

three_GPP_Compliant_Scenario_Validation_Launcher;

close(fwb);

sendmail(addr,subj,[EndMsg,Sgnt]);