addr = {'yuxiao.zhai@mail.utoronto.ca','yu.xue@mail.utoronto.ca'};
subj = 'Message From Amanda';
sgnt = [newline,newline,'This message is automatically generated by MATLAB. Please do not reply.'];

msg = 'Simulation started.';

sendmail(addr,subj,[msg,sgnt]);

three_GPP_Compliant_Scenario_Validation_Launcher

msg = 'Simulation finished.';
sendmail(addr,subj,[msg,sgnt]);
